CREATE OR REPLACE PACKAGE WS_REF_CURSOR_SQL AS

  TYPE cursorType IS REF CURSOR;

  FUNCTION GET_OBJECTS_BY_NAME(I_xml IN CLOB)
  RETURN cursorType;
  
  FUNCTION GET_OBJECTS_BY_OWNER(I_xml IN CLOB)
  RETURN cursorType;

END WS_REF_CURSOR_SQL;
/

show errors PACKAGE WS_REF_CURSOR_SQL;
 